CREATE TABLE "GCG_6734_SP_PRT_COMM"(
 "PART" CHAR(20),
 "CUSTOMER" CHAR(6),
 "SP_ID" CHAR(3),
 "RATE" DOUBLE);

CREATE INDEX "GCG_6734_SP_PRT_COMM" ON "GCG_6734_SP_PRT_COMM"("PART", "CUSTOMER", "SP_ID");